
services:
  nightscout:
    build:
      context: ./cgm-remote-monitor
      args:
        NIGHTSCOUT_VERSION: "${NIGHTSCOUT_VERSION:?}"
    image: "nightscout/cgm-remote-monitor:${NIGHTSCOUT_VERSION:?}-secrets"

  caddy:
    build:
      context: ./caddy
      args:
        CADDY_VERSION: "${CADDY_VERSION:?}"
        CADDY_CLOUDFLARE_VERSION: "${CADDY_CLOUDFLARE_VERSION:?}"
    image: "caddy:${CADDY_VERSION:?}-cloudflare"
