
services:
  mongo:
    image: mongo:4.4
    restart: unless-stopped
    volumes:
      - mongo_config:/data/configdb
      - mongo_data:/data/db

  nightscout:
    image: "nightscout/cgm-remote-monitor:${NIGHTSCOUT_VERSION:?}-secrets"
    container_name: nightscout
    restart: unless-stopped
    depends_on:
      - mongo
    expose:
      - 1337
    environment:
      NODE_ENV: production
      TZ: "${NIGHTSCOUT_TIMEZONE:?}"

      # MONGO_CONNECTION - The connection string for your Mongo database.
      # Something like mongodb://sally:sallypass@ds099999.mongolab.com:99999/nightscout
      # The default connects to the `mongo` included in this docker-compose file.
      # If you change it, you probably also want to comment out the entire `mongo` service block
      # and `depends_on` block above.
      MONGO_CONNECTION: mongodb://mongo:27017/nightscout

      # API_SECRET_FILE - A file that contains a secret passphrase which must be at least 12 characters long.
      API_SECRET_FILE: /run/secrets/nightscout_api_secret

      # ENABLE - Used to enable optional features, expects a space delimited list, such as: careportal rawbg iob
      # See https://github.com/nightscout/cgm-remote-monitor#plugins for details
      ENABLE: careportal rawbg iob

      # AUTH_DEFAULT_ROLES (readable) - possible values readable, denied, or any valid role name.
      # When readable, anyone can view Nightscout without a token. Setting it to denied will require
      # a token from every visit, using status-only will enable api-secret based login.
      AUTH_DEFAULT_ROLES: denied

      # BASE_URL - Used for building links to your site's API, i.e. Pushover callbacks, usually the URL
      # of your Nightscout site.
      BASE_URL: "https://nightscout.${DOMAIN_NAME:?}"

      # For all other settings, please refer to the Environment section of the README
      # https://github.com/nightscout/cgm-remote-monitor#environment
    secrets:
      - nightscout_api_secret

  caddy:
    image: "caddy:${CADDY_VERSION:?}-cloudflare"
    container_name: caddy
    restart: unless-stopped
    ports:
      - 8443:443
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_config:/config
      - caddy_data:/data
    environment:
      DOMAIN_NAME: "${DOMAIN_NAME:?}"
    secrets:
      - cloudflare_api_token

  cloudflared:
    image: cloudflare/cloudflared:2024.8.3
    command: tunnel run --credentials-file /run/secrets/cloudflare_tunnel_cred "${CLOUDFLARE_TUNNEL_NAME:?}"
    restart: unless-stopped
    depends_on:
      - caddy
    secrets:
      - cloudflare_tunnel_cred

secrets:
  nightscout_api_secret:
    external: true
  cloudflare_api_token:
    external: true
  cloudflare_tunnel_cred:
    external: true

volumes:
  mongo_config:
  mongo_data:
  caddy_config:
  caddy_data:
