
services:
  caddy:
    build:
      context: ./caddy
      args:
        CADDY_VERSION: "${CADDY_VERSION:?}"
        CLOUDFLARE_VERSION: "${CLOUDFLARE_VERSION:?}"
    image: "caddy:${CADDY_VERSION:?}-cloudflare"
