
x-logging:
  &default-logging
  options:
    max-size: '10m'
    max-file: '5'
  driver: json-file

services:
  mongo:
    image: mongo:4.4
    restart: unless-stopped
    volumes:
      - mongo_config:/data/configdb
      - mongo_data:/data/db
    logging: *default-logging

  nightscout:
    image: nightscout/cgm-remote-monitor:15.0.2
    container_name: nightscout
    restart: unless-stopped
    depends_on:
      - mongo
    logging: *default-logging
    environment:
      NODE_ENV: production
      TZ: ${NIGHTSCOUT_TIMEZONE}

      # INSECURE_USE_HTTP (false) - Redirect unsafe http traffic to https. Possible values false, or true.
      # Your site redirects to https by default. If you don't want that from Nightscout, but want to
      # implement that with a Nginx or Apache proxy, set INSECURE_USE_HTTP to true. Note: This will allow
      # (unsafe) http traffic to your Nightscout instance and is not recommended.
      #
      # In this case, the `nightscout` service can use HTTP, because we will use a proxy to serve the HTTPS
      # and manage TLS certificates
      INSECURE_USE_HTTP: 'true'

      # MONGO_CONNECTION - The connection string for your Mongo database.
      # Something like mongodb://sally:sallypass@ds099999.mongolab.com:99999/nightscout
      # The default connects to the `mongo` included in this docker-compose file.
      # If you change it, you probably also want to comment out the entire `mongo` service block
      # and `depends_on` block above.
      MONGO_CONNECTION: mongodb://mongo:27017/nightscout

      # API_SECRET - A secret passphrase that must be at least 12 characters long.
      API_SECRET: ${NIGHTSCOUT_API_SECRET}

      # ENABLE - Used to enable optional features, expects a space delimited list, such as: careportal rawbg iob
      # See https://github.com/nightscout/cgm-remote-monitor#plugins for details
      ENABLE: careportal rawbg iob

      # AUTH_DEFAULT_ROLES (readable) - possible values readable, denied, or any valid role name.
      # When readable, anyone can view Nightscout without a token. Setting it to denied will require
      # a token from every visit, using status-only will enable api-secret based login.
      AUTH_DEFAULT_ROLES: readable

      # BASE_URL - Used for building links to your site's API, i.e. Pushover callbacks, usually the URL
      # of your Nightscout site.
      BASE_URL: "http://nightscout.${DOMAIN_NAME}"

      # PORT (1337) - The port that the node.js application will listen on.
      PORT: 1337

      # For all other settings, please refer to the Environment section of the README
      # https://github.com/nightscout/cgm-remote-monitor#environment
    expose:
      - 1337

  caddy:
    image: caddy:2.8.4
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - $PWD/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_config:/config
      - caddy_data:/data
    logging: *default-logging
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}

volumes:
  mongo_config:
  mongo_data:
  caddy_config:
  caddy_data:
