
services:
  mongo:
    networks:
      - backend

  nightscout:
    networks:
      - backend

  caddy:
    networks:
      - backend
      - revproxy

  cloudflared:
    networks:
      - revproxy

networks:
  backend:
  revproxy:
