version: '3'

env:
  COMPOSE_ENV_FILES: .env,.env.local

vars:
  DOCKER:
    sh: which podman || which docker

run: when_changed

tasks:
  configure-local:
    cmds:
      - ./configure_local.sh
    interactive: true
    sources:
      - configure_local.sh
    generates:
      - .env.local

  configure-secrets:
    deps: [configure-local]
    cmds:
      - ./configure_secrets.sh
    interactive: true
    sources:
      - configure_secrets.sh
    generates:
      - .env.secrets

  install-secrets:
    deps: [configure-secrets]
    vars:
      MISSING_SECRETS:
        sh: >
          grep -v COMPOSE_FILE .env.secrets | awk -F= '{print tolower($1)}' |
            xargs -I{} sh -c '{{.DOCKER}} secret exists {} || printf "%s\n" {}'
    cmds:
      - for: { var: MISSING_SECRETS }
        cmd: sed -n 's/^{{.ITEM}}=//ip' .env.secrets | {{.DOCKER}} secret create {{.ITEM}} -
    preconditions:
      - sh: test {{base .DOCKER}} = podman
        msg: Installation of secrets is only supported when using podman.
    status:
      - test {{len .MISSING_SECRETS}} -eq 0

  images:
    deps: [configure-local]
    vars:
      MISSING_IMAGES:
        sh: >
          comm -23
          <({{.DOCKER}} compose config --images | sort)
          <({{.DOCKER}} images --filter dangling=false --format {{`{{.Repository}}:{{.Tag}}`}} |
            sed -E 's|^docker.io/(library/)?||' | sort)
    cmds:
      - echo "Couldn't find the following images:"
      - for: { var: MISSING_IMAGES }
        cmd: printf '%s\n' {{.ITEM}}
      - '{{.DOCKER}} compose pull cloudflared mongo'
      - '{{.DOCKER}} compose build nightscout caddy'
    status:
      - test {{len .MISSING_IMAGES}} -eq 0

  ps:
    deps: [configure-local]
    cmds:
      - '{{.DOCKER}} compose ps'

  up:
    deps: [configure-secrets, images]
    env:
      COMPOSE_ENV_FILES: '{{printf "%s,.env.secrets" .COMPOSE_ENV_FILES}}'
    cmds:
      - '{{.DOCKER}} compose up --detach'

  down:
    deps: [configure-secrets, images]
    env:
      COMPOSE_ENV_FILES: '{{printf "%s,.env.secrets" .COMPOSE_ENV_FILES}}'
    cmds:
      - '{{.DOCKER}} compose down'

  default:
    deps: [ps]
